package com.may.mybatis.model;

import java.util.Date;

public class KeyVallueConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.id
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.rkey
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private String rkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.rvalue
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private String rvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.remark
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.isused
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private String isused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.create_date
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.create_person
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.update_date
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_Vallue_config.update_person
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.id
     *
     * @return the value of key_Vallue_config.id
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.id
     *
     * @param id the value for key_Vallue_config.id
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.rkey
     *
     * @return the value of key_Vallue_config.rkey
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getRkey() {
        return rkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.rkey
     *
     * @param rkey the value for key_Vallue_config.rkey
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setRkey(String rkey) {
        this.rkey = rkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.rvalue
     *
     * @return the value of key_Vallue_config.rvalue
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getRvalue() {
        return rvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.rvalue
     *
     * @param rvalue the value for key_Vallue_config.rvalue
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setRvalue(String rvalue) {
        this.rvalue = rvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.remark
     *
     * @return the value of key_Vallue_config.remark
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.remark
     *
     * @param remark the value for key_Vallue_config.remark
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.isused
     *
     * @return the value of key_Vallue_config.isused
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.isused
     *
     * @param isused the value for key_Vallue_config.isused
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setIsused(String isused) {
        this.isused = isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.create_date
     *
     * @return the value of key_Vallue_config.create_date
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.create_date
     *
     * @param createDate the value for key_Vallue_config.create_date
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.create_person
     *
     * @return the value of key_Vallue_config.create_person
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.create_person
     *
     * @param createPerson the value for key_Vallue_config.create_person
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.update_date
     *
     * @return the value of key_Vallue_config.update_date
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.update_date
     *
     * @param updateDate the value for key_Vallue_config.update_date
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_Vallue_config.update_person
     *
     * @return the value of key_Vallue_config.update_person
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_Vallue_config.update_person
     *
     * @param updatePerson the value for key_Vallue_config.update_person
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}