package com.may.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReleaseSystemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public ReleaseSystemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNull() {
            addCriterion("system_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNotNull() {
            addCriterion("system_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNameEqualTo(String value) {
            addCriterion("system_name =", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotEqualTo(String value) {
            addCriterion("system_name <>", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThan(String value) {
            addCriterion("system_name >", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_name >=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThan(String value) {
            addCriterion("system_name <", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThanOrEqualTo(String value) {
            addCriterion("system_name <=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLike(String value) {
            addCriterion("system_name like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotLike(String value) {
            addCriterion("system_name not like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameIn(List<String> values) {
            addCriterion("system_name in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotIn(List<String> values) {
            addCriterion("system_name not in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameBetween(String value1, String value2) {
            addCriterion("system_name between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotBetween(String value1, String value2) {
            addCriterion("system_name not between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkIsNull() {
            addCriterion("system_remark is null");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkIsNotNull() {
            addCriterion("system_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkEqualTo(String value) {
            addCriterion("system_remark =", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkNotEqualTo(String value) {
            addCriterion("system_remark <>", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkGreaterThan(String value) {
            addCriterion("system_remark >", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("system_remark >=", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkLessThan(String value) {
            addCriterion("system_remark <", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkLessThanOrEqualTo(String value) {
            addCriterion("system_remark <=", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkLike(String value) {
            addCriterion("system_remark like", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkNotLike(String value) {
            addCriterion("system_remark not like", value, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkIn(List<String> values) {
            addCriterion("system_remark in", values, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkNotIn(List<String> values) {
            addCriterion("system_remark not in", values, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkBetween(String value1, String value2) {
            addCriterion("system_remark between", value1, value2, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andSystemRemarkNotBetween(String value1, String value2) {
            addCriterion("system_remark not between", value1, value2, "systemRemark");
            return (Criteria) this;
        }

        public Criteria andCreatePersionIsNull() {
            addCriterion("create_persion is null");
            return (Criteria) this;
        }

        public Criteria andCreatePersionIsNotNull() {
            addCriterion("create_persion is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePersionEqualTo(String value) {
            addCriterion("create_persion =", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionNotEqualTo(String value) {
            addCriterion("create_persion <>", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionGreaterThan(String value) {
            addCriterion("create_persion >", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionGreaterThanOrEqualTo(String value) {
            addCriterion("create_persion >=", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionLessThan(String value) {
            addCriterion("create_persion <", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionLessThanOrEqualTo(String value) {
            addCriterion("create_persion <=", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionLike(String value) {
            addCriterion("create_persion like", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionNotLike(String value) {
            addCriterion("create_persion not like", value, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionIn(List<String> values) {
            addCriterion("create_persion in", values, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionNotIn(List<String> values) {
            addCriterion("create_persion not in", values, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionBetween(String value1, String value2) {
            addCriterion("create_persion between", value1, value2, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreatePersionNotBetween(String value1, String value2) {
            addCriterion("create_persion not between", value1, value2, "createPersion");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionIsNull() {
            addCriterion("update_persion is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionIsNotNull() {
            addCriterion("update_persion is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionEqualTo(String value) {
            addCriterion("update_persion =", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionNotEqualTo(String value) {
            addCriterion("update_persion <>", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionGreaterThan(String value) {
            addCriterion("update_persion >", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionGreaterThanOrEqualTo(String value) {
            addCriterion("update_persion >=", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionLessThan(String value) {
            addCriterion("update_persion <", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionLessThanOrEqualTo(String value) {
            addCriterion("update_persion <=", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionLike(String value) {
            addCriterion("update_persion like", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionNotLike(String value) {
            addCriterion("update_persion not like", value, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionIn(List<String> values) {
            addCriterion("update_persion in", values, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionNotIn(List<String> values) {
            addCriterion("update_persion not in", values, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionBetween(String value1, String value2) {
            addCriterion("update_persion between", value1, value2, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdatePersionNotBetween(String value1, String value2) {
            addCriterion("update_persion not between", value1, value2, "updatePersion");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andIsUsedIsNull() {
            addCriterion("is_used is null");
            return (Criteria) this;
        }

        public Criteria andIsUsedIsNotNull() {
            addCriterion("is_used is not null");
            return (Criteria) this;
        }

        public Criteria andIsUsedEqualTo(String value) {
            addCriterion("is_used =", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotEqualTo(String value) {
            addCriterion("is_used <>", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedGreaterThan(String value) {
            addCriterion("is_used >", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedGreaterThanOrEqualTo(String value) {
            addCriterion("is_used >=", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedLessThan(String value) {
            addCriterion("is_used <", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedLessThanOrEqualTo(String value) {
            addCriterion("is_used <=", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedLike(String value) {
            addCriterion("is_used like", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotLike(String value) {
            addCriterion("is_used not like", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedIn(List<String> values) {
            addCriterion("is_used in", values, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotIn(List<String> values) {
            addCriterion("is_used not in", values, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedBetween(String value1, String value2) {
            addCriterion("is_used between", value1, value2, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotBetween(String value1, String value2) {
            addCriterion("is_used not between", value1, value2, "isUsed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table releaseSystem
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 13 20:29:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}