package com.may.mybatis.model;

import java.util.Date;

public class ReleaseList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.systemName
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String systemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.release_mark
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String releaseMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.createDate
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.createPerson
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String createperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.updateDate
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.updatePerson
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String updateperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.isUsed
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String isused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.ispublish
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String ispublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.releasePersonId
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String releasepersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.releasePersonName
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String releasepersonname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.systemID
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String systemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.pathList
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String pathlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.id
     *
     * @return the value of Release_list.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.id
     *
     * @param id the value for Release_list.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.systemName
     *
     * @return the value of Release_list.systemName
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.systemName
     *
     * @param systemname the value for Release_list.systemName
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.release_mark
     *
     * @return the value of Release_list.release_mark
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getReleaseMark() {
        return releaseMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.release_mark
     *
     * @param releaseMark the value for Release_list.release_mark
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setReleaseMark(String releaseMark) {
        this.releaseMark = releaseMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.createDate
     *
     * @return the value of Release_list.createDate
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.createDate
     *
     * @param createdate the value for Release_list.createDate
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.createPerson
     *
     * @return the value of Release_list.createPerson
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.createPerson
     *
     * @param createperson the value for Release_list.createPerson
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.updateDate
     *
     * @return the value of Release_list.updateDate
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.updateDate
     *
     * @param updatedate the value for Release_list.updateDate
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.updatePerson
     *
     * @return the value of Release_list.updatePerson
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getUpdateperson() {
        return updateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.updatePerson
     *
     * @param updateperson the value for Release_list.updatePerson
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setUpdateperson(String updateperson) {
        this.updateperson = updateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.isUsed
     *
     * @return the value of Release_list.isUsed
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.isUsed
     *
     * @param isused the value for Release_list.isUsed
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setIsused(String isused) {
        this.isused = isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.ispublish
     *
     * @return the value of Release_list.ispublish
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getIspublish() {
        return ispublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.ispublish
     *
     * @param ispublish the value for Release_list.ispublish
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setIspublish(String ispublish) {
        this.ispublish = ispublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.releasePersonId
     *
     * @return the value of Release_list.releasePersonId
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getReleasepersonid() {
        return releasepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.releasePersonId
     *
     * @param releasepersonid the value for Release_list.releasePersonId
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setReleasepersonid(String releasepersonid) {
        this.releasepersonid = releasepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.releasePersonName
     *
     * @return the value of Release_list.releasePersonName
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getReleasepersonname() {
        return releasepersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.releasePersonName
     *
     * @param releasepersonname the value for Release_list.releasePersonName
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setReleasepersonname(String releasepersonname) {
        this.releasepersonname = releasepersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.systemID
     *
     * @return the value of Release_list.systemID
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getSystemid() {
        return systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.systemID
     *
     * @param systemid the value for Release_list.systemID
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.pathList
     *
     * @return the value of Release_list.pathList
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getPathlist() {
        return pathlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.pathList
     *
     * @param pathlist the value for Release_list.pathList
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setPathlist(String pathlist) {
        this.pathlist = pathlist;
    }
}