package com.may.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReleaseListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public ReleaseListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNull() {
            addCriterion("systemName is null");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNotNull() {
            addCriterion("systemName is not null");
            return (Criteria) this;
        }

        public Criteria andSystemnameEqualTo(String value) {
            addCriterion("systemName =", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotEqualTo(String value) {
            addCriterion("systemName <>", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThan(String value) {
            addCriterion("systemName >", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThanOrEqualTo(String value) {
            addCriterion("systemName >=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThan(String value) {
            addCriterion("systemName <", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThanOrEqualTo(String value) {
            addCriterion("systemName <=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLike(String value) {
            addCriterion("systemName like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotLike(String value) {
            addCriterion("systemName not like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameIn(List<String> values) {
            addCriterion("systemName in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotIn(List<String> values) {
            addCriterion("systemName not in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameBetween(String value1, String value2) {
            addCriterion("systemName between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotBetween(String value1, String value2) {
            addCriterion("systemName not between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkIsNull() {
            addCriterion("release_mark is null");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkIsNotNull() {
            addCriterion("release_mark is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkEqualTo(String value) {
            addCriterion("release_mark =", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkNotEqualTo(String value) {
            addCriterion("release_mark <>", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkGreaterThan(String value) {
            addCriterion("release_mark >", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkGreaterThanOrEqualTo(String value) {
            addCriterion("release_mark >=", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkLessThan(String value) {
            addCriterion("release_mark <", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkLessThanOrEqualTo(String value) {
            addCriterion("release_mark <=", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkLike(String value) {
            addCriterion("release_mark like", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkNotLike(String value) {
            addCriterion("release_mark not like", value, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkIn(List<String> values) {
            addCriterion("release_mark in", values, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkNotIn(List<String> values) {
            addCriterion("release_mark not in", values, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkBetween(String value1, String value2) {
            addCriterion("release_mark between", value1, value2, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andReleaseMarkNotBetween(String value1, String value2) {
            addCriterion("release_mark not between", value1, value2, "releaseMark");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatepersonIsNull() {
            addCriterion("createPerson is null");
            return (Criteria) this;
        }

        public Criteria andCreatepersonIsNotNull() {
            addCriterion("createPerson is not null");
            return (Criteria) this;
        }

        public Criteria andCreatepersonEqualTo(String value) {
            addCriterion("createPerson =", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotEqualTo(String value) {
            addCriterion("createPerson <>", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonGreaterThan(String value) {
            addCriterion("createPerson >", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonGreaterThanOrEqualTo(String value) {
            addCriterion("createPerson >=", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonLessThan(String value) {
            addCriterion("createPerson <", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonLessThanOrEqualTo(String value) {
            addCriterion("createPerson <=", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonLike(String value) {
            addCriterion("createPerson like", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotLike(String value) {
            addCriterion("createPerson not like", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonIn(List<String> values) {
            addCriterion("createPerson in", values, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotIn(List<String> values) {
            addCriterion("createPerson not in", values, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonBetween(String value1, String value2) {
            addCriterion("createPerson between", value1, value2, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotBetween(String value1, String value2) {
            addCriterion("createPerson not between", value1, value2, "createperson");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("updateDate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("updateDate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("updateDate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("updateDate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("updateDate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("updateDate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("updateDate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("updateDate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("updateDate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("updateDate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("updateDate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("updateDate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonIsNull() {
            addCriterion("updatePerson is null");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonIsNotNull() {
            addCriterion("updatePerson is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonEqualTo(String value) {
            addCriterion("updatePerson =", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonNotEqualTo(String value) {
            addCriterion("updatePerson <>", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonGreaterThan(String value) {
            addCriterion("updatePerson >", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonGreaterThanOrEqualTo(String value) {
            addCriterion("updatePerson >=", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonLessThan(String value) {
            addCriterion("updatePerson <", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonLessThanOrEqualTo(String value) {
            addCriterion("updatePerson <=", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonLike(String value) {
            addCriterion("updatePerson like", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonNotLike(String value) {
            addCriterion("updatePerson not like", value, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonIn(List<String> values) {
            addCriterion("updatePerson in", values, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonNotIn(List<String> values) {
            addCriterion("updatePerson not in", values, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonBetween(String value1, String value2) {
            addCriterion("updatePerson between", value1, value2, "updateperson");
            return (Criteria) this;
        }

        public Criteria andUpdatepersonNotBetween(String value1, String value2) {
            addCriterion("updatePerson not between", value1, value2, "updateperson");
            return (Criteria) this;
        }

        public Criteria andIsusedIsNull() {
            addCriterion("isUsed is null");
            return (Criteria) this;
        }

        public Criteria andIsusedIsNotNull() {
            addCriterion("isUsed is not null");
            return (Criteria) this;
        }

        public Criteria andIsusedEqualTo(String value) {
            addCriterion("isUsed =", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotEqualTo(String value) {
            addCriterion("isUsed <>", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedGreaterThan(String value) {
            addCriterion("isUsed >", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedGreaterThanOrEqualTo(String value) {
            addCriterion("isUsed >=", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedLessThan(String value) {
            addCriterion("isUsed <", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedLessThanOrEqualTo(String value) {
            addCriterion("isUsed <=", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedLike(String value) {
            addCriterion("isUsed like", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotLike(String value) {
            addCriterion("isUsed not like", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedIn(List<String> values) {
            addCriterion("isUsed in", values, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotIn(List<String> values) {
            addCriterion("isUsed not in", values, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedBetween(String value1, String value2) {
            addCriterion("isUsed between", value1, value2, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotBetween(String value1, String value2) {
            addCriterion("isUsed not between", value1, value2, "isused");
            return (Criteria) this;
        }

        public Criteria andIspublishIsNull() {
            addCriterion("ispublish is null");
            return (Criteria) this;
        }

        public Criteria andIspublishIsNotNull() {
            addCriterion("ispublish is not null");
            return (Criteria) this;
        }

        public Criteria andIspublishEqualTo(String value) {
            addCriterion("ispublish =", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishNotEqualTo(String value) {
            addCriterion("ispublish <>", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishGreaterThan(String value) {
            addCriterion("ispublish >", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishGreaterThanOrEqualTo(String value) {
            addCriterion("ispublish >=", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishLessThan(String value) {
            addCriterion("ispublish <", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishLessThanOrEqualTo(String value) {
            addCriterion("ispublish <=", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishLike(String value) {
            addCriterion("ispublish like", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishNotLike(String value) {
            addCriterion("ispublish not like", value, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishIn(List<String> values) {
            addCriterion("ispublish in", values, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishNotIn(List<String> values) {
            addCriterion("ispublish not in", values, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishBetween(String value1, String value2) {
            addCriterion("ispublish between", value1, value2, "ispublish");
            return (Criteria) this;
        }

        public Criteria andIspublishNotBetween(String value1, String value2) {
            addCriterion("ispublish not between", value1, value2, "ispublish");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidIsNull() {
            addCriterion("releasePersonId is null");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidIsNotNull() {
            addCriterion("releasePersonId is not null");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidEqualTo(String value) {
            addCriterion("releasePersonId =", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidNotEqualTo(String value) {
            addCriterion("releasePersonId <>", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidGreaterThan(String value) {
            addCriterion("releasePersonId >", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidGreaterThanOrEqualTo(String value) {
            addCriterion("releasePersonId >=", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidLessThan(String value) {
            addCriterion("releasePersonId <", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidLessThanOrEqualTo(String value) {
            addCriterion("releasePersonId <=", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidLike(String value) {
            addCriterion("releasePersonId like", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidNotLike(String value) {
            addCriterion("releasePersonId not like", value, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidIn(List<String> values) {
            addCriterion("releasePersonId in", values, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidNotIn(List<String> values) {
            addCriterion("releasePersonId not in", values, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidBetween(String value1, String value2) {
            addCriterion("releasePersonId between", value1, value2, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonidNotBetween(String value1, String value2) {
            addCriterion("releasePersonId not between", value1, value2, "releasepersonid");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameIsNull() {
            addCriterion("releasePersonName is null");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameIsNotNull() {
            addCriterion("releasePersonName is not null");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameEqualTo(String value) {
            addCriterion("releasePersonName =", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameNotEqualTo(String value) {
            addCriterion("releasePersonName <>", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameGreaterThan(String value) {
            addCriterion("releasePersonName >", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameGreaterThanOrEqualTo(String value) {
            addCriterion("releasePersonName >=", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameLessThan(String value) {
            addCriterion("releasePersonName <", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameLessThanOrEqualTo(String value) {
            addCriterion("releasePersonName <=", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameLike(String value) {
            addCriterion("releasePersonName like", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameNotLike(String value) {
            addCriterion("releasePersonName not like", value, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameIn(List<String> values) {
            addCriterion("releasePersonName in", values, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameNotIn(List<String> values) {
            addCriterion("releasePersonName not in", values, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameBetween(String value1, String value2) {
            addCriterion("releasePersonName between", value1, value2, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andReleasepersonnameNotBetween(String value1, String value2) {
            addCriterion("releasePersonName not between", value1, value2, "releasepersonname");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNull() {
            addCriterion("systemID is null");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNotNull() {
            addCriterion("systemID is not null");
            return (Criteria) this;
        }

        public Criteria andSystemidEqualTo(String value) {
            addCriterion("systemID =", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotEqualTo(String value) {
            addCriterion("systemID <>", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThan(String value) {
            addCriterion("systemID >", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThanOrEqualTo(String value) {
            addCriterion("systemID >=", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidLessThan(String value) {
            addCriterion("systemID <", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidLessThanOrEqualTo(String value) {
            addCriterion("systemID <=", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidLike(String value) {
            addCriterion("systemID like", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotLike(String value) {
            addCriterion("systemID not like", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidIn(List<String> values) {
            addCriterion("systemID in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotIn(List<String> values) {
            addCriterion("systemID not in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidBetween(String value1, String value2) {
            addCriterion("systemID between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotBetween(String value1, String value2) {
            addCriterion("systemID not between", value1, value2, "systemid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Release_list
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 13 20:29:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}