package com.may.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReleasePersonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public ReleasePersonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReleasenameIsNull() {
            addCriterion("releaseName is null");
            return (Criteria) this;
        }

        public Criteria andReleasenameIsNotNull() {
            addCriterion("releaseName is not null");
            return (Criteria) this;
        }

        public Criteria andReleasenameEqualTo(String value) {
            addCriterion("releaseName =", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameNotEqualTo(String value) {
            addCriterion("releaseName <>", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameGreaterThan(String value) {
            addCriterion("releaseName >", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameGreaterThanOrEqualTo(String value) {
            addCriterion("releaseName >=", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameLessThan(String value) {
            addCriterion("releaseName <", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameLessThanOrEqualTo(String value) {
            addCriterion("releaseName <=", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameLike(String value) {
            addCriterion("releaseName like", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameNotLike(String value) {
            addCriterion("releaseName not like", value, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameIn(List<String> values) {
            addCriterion("releaseName in", values, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameNotIn(List<String> values) {
            addCriterion("releaseName not in", values, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameBetween(String value1, String value2) {
            addCriterion("releaseName between", value1, value2, "releasename");
            return (Criteria) this;
        }

        public Criteria andReleasenameNotBetween(String value1, String value2) {
            addCriterion("releaseName not between", value1, value2, "releasename");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("updateDate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("updateDate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("updateDate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("updateDate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("updateDate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("updateDate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("updateDate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("updateDate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("updateDate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("updateDate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("updateDate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("updateDate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andIsusedIsNull() {
            addCriterion("isUsed is null");
            return (Criteria) this;
        }

        public Criteria andIsusedIsNotNull() {
            addCriterion("isUsed is not null");
            return (Criteria) this;
        }

        public Criteria andIsusedEqualTo(String value) {
            addCriterion("isUsed =", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotEqualTo(String value) {
            addCriterion("isUsed <>", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedGreaterThan(String value) {
            addCriterion("isUsed >", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedGreaterThanOrEqualTo(String value) {
            addCriterion("isUsed >=", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedLessThan(String value) {
            addCriterion("isUsed <", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedLessThanOrEqualTo(String value) {
            addCriterion("isUsed <=", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedLike(String value) {
            addCriterion("isUsed like", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotLike(String value) {
            addCriterion("isUsed not like", value, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedIn(List<String> values) {
            addCriterion("isUsed in", values, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotIn(List<String> values) {
            addCriterion("isUsed not in", values, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedBetween(String value1, String value2) {
            addCriterion("isUsed between", value1, value2, "isused");
            return (Criteria) this;
        }

        public Criteria andIsusedNotBetween(String value1, String value2) {
            addCriterion("isUsed not between", value1, value2, "isused");
            return (Criteria) this;
        }

        public Criteria andSystemcodeIsNull() {
            addCriterion("systemCode is null");
            return (Criteria) this;
        }

        public Criteria andSystemcodeIsNotNull() {
            addCriterion("systemCode is not null");
            return (Criteria) this;
        }

        public Criteria andSystemcodeEqualTo(String value) {
            addCriterion("systemCode =", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeNotEqualTo(String value) {
            addCriterion("systemCode <>", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeGreaterThan(String value) {
            addCriterion("systemCode >", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeGreaterThanOrEqualTo(String value) {
            addCriterion("systemCode >=", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeLessThan(String value) {
            addCriterion("systemCode <", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeLessThanOrEqualTo(String value) {
            addCriterion("systemCode <=", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeLike(String value) {
            addCriterion("systemCode like", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeNotLike(String value) {
            addCriterion("systemCode not like", value, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeIn(List<String> values) {
            addCriterion("systemCode in", values, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeNotIn(List<String> values) {
            addCriterion("systemCode not in", values, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeBetween(String value1, String value2) {
            addCriterion("systemCode between", value1, value2, "systemcode");
            return (Criteria) this;
        }

        public Criteria andSystemcodeNotBetween(String value1, String value2) {
            addCriterion("systemCode not between", value1, value2, "systemcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table releasePerson
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 13 11:08:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}