package com.may.mybatis.model;

import java.util.Date;

public class ReleaseSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.system_name
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.system_remark
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String systemRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.create_persion
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String createPersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.create_date
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.update_persion
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String updatePersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.update_date
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem.is_used
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private String isUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.id
     *
     * @return the value of releaseSystem.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.id
     *
     * @param id the value for releaseSystem.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.system_name
     *
     * @return the value of releaseSystem.system_name
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.system_name
     *
     * @param systemName the value for releaseSystem.system_name
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.system_remark
     *
     * @return the value of releaseSystem.system_remark
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getSystemRemark() {
        return systemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.system_remark
     *
     * @param systemRemark the value for releaseSystem.system_remark
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setSystemRemark(String systemRemark) {
        this.systemRemark = systemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.create_persion
     *
     * @return the value of releaseSystem.create_persion
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getCreatePersion() {
        return createPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.create_persion
     *
     * @param createPersion the value for releaseSystem.create_persion
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setCreatePersion(String createPersion) {
        this.createPersion = createPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.create_date
     *
     * @return the value of releaseSystem.create_date
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.create_date
     *
     * @param createDate the value for releaseSystem.create_date
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.update_persion
     *
     * @return the value of releaseSystem.update_persion
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getUpdatePersion() {
        return updatePersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.update_persion
     *
     * @param updatePersion the value for releaseSystem.update_persion
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setUpdatePersion(String updatePersion) {
        this.updatePersion = updatePersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.update_date
     *
     * @return the value of releaseSystem.update_date
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.update_date
     *
     * @param updateDate the value for releaseSystem.update_date
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem.is_used
     *
     * @return the value of releaseSystem.is_used
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public String getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem.is_used
     *
     * @param isUsed the value for releaseSystem.is_used
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setIsUsed(String isUsed) {
        this.isUsed = isUsed;
    }
}