package com.may.mybatis.model;

import java.util.Date;

public class ReleasePerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.id
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.releaseName
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private String releasename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.createDate
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.updateDate
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.isUsed
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private String isused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.systemCode
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private String systemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releasePerson.remark
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.id
     *
     * @return the value of releasePerson.id
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.id
     *
     * @param id the value for releasePerson.id
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.releaseName
     *
     * @return the value of releasePerson.releaseName
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public String getReleasename() {
        return releasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.releaseName
     *
     * @param releasename the value for releasePerson.releaseName
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setReleasename(String releasename) {
        this.releasename = releasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.createDate
     *
     * @return the value of releasePerson.createDate
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.createDate
     *
     * @param createdate the value for releasePerson.createDate
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.updateDate
     *
     * @return the value of releasePerson.updateDate
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.updateDate
     *
     * @param updatedate the value for releasePerson.updateDate
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.isUsed
     *
     * @return the value of releasePerson.isUsed
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public String getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.isUsed
     *
     * @param isused the value for releasePerson.isUsed
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setIsused(String isused) {
        this.isused = isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.systemCode
     *
     * @return the value of releasePerson.systemCode
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.systemCode
     *
     * @param systemcode the value for releasePerson.systemCode
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releasePerson.remark
     *
     * @return the value of releasePerson.remark
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releasePerson.remark
     *
     * @param remark the value for releasePerson.remark
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}