package com.may.mybatis.model;

public class ReleaseSystemPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem_person.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem_person.releaseSystemid
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Integer releasesystemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column releaseSystem_person.releasepersonId
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    private Integer releasepersonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem_person.id
     *
     * @return the value of releaseSystem_person.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem_person.id
     *
     * @param id the value for releaseSystem_person.id
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem_person.releaseSystemid
     *
     * @return the value of releaseSystem_person.releaseSystemid
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Integer getReleasesystemid() {
        return releasesystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem_person.releaseSystemid
     *
     * @param releasesystemid the value for releaseSystem_person.releaseSystemid
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setReleasesystemid(Integer releasesystemid) {
        this.releasesystemid = releasesystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column releaseSystem_person.releasepersonId
     *
     * @return the value of releaseSystem_person.releasepersonId
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public Integer getReleasepersonid() {
        return releasepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column releaseSystem_person.releasepersonId
     *
     * @param releasepersonid the value for releaseSystem_person.releasepersonId
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    public void setReleasepersonid(Integer releasepersonid) {
        this.releasepersonid = releasepersonid;
    }
}