package com.may.mybatis.model;

import java.util.Date;

public class ReleaseList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.id
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.release_mark
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private String releaseMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.createDate
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.createPerson
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private String createperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.updateDate
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.updatePerson
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private Date updateperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Release_list.isUsed
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    private String isused;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.id
     *
     * @return the value of Release_list.id
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.id
     *
     * @param id the value for Release_list.id
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.release_mark
     *
     * @return the value of Release_list.release_mark
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public String getReleaseMark() {
        return releaseMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.release_mark
     *
     * @param releaseMark the value for Release_list.release_mark
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setReleaseMark(String releaseMark) {
        this.releaseMark = releaseMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.createDate
     *
     * @return the value of Release_list.createDate
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.createDate
     *
     * @param createdate the value for Release_list.createDate
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.createPerson
     *
     * @return the value of Release_list.createPerson
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.createPerson
     *
     * @param createperson the value for Release_list.createPerson
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.updateDate
     *
     * @return the value of Release_list.updateDate
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.updateDate
     *
     * @param updatedate the value for Release_list.updateDate
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.updatePerson
     *
     * @return the value of Release_list.updatePerson
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public Date getUpdateperson() {
        return updateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.updatePerson
     *
     * @param updateperson the value for Release_list.updatePerson
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setUpdateperson(Date updateperson) {
        this.updateperson = updateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Release_list.isUsed
     *
     * @return the value of Release_list.isUsed
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public String getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Release_list.isUsed
     *
     * @param isused the value for Release_list.isUsed
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    public void setIsused(String isused) {
        this.isused = isused;
    }
}