package com.may.mybatis.model;

import java.util.Date;

public class RootDirectories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.id
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.directoriey_name
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private String directorieyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.isUsed
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private String isused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.create_date
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.create_persion
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private String createPersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.update_date
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.update_persion
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private String updatePersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_directories.sys_id
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    private String sysId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.id
     *
     * @return the value of root_directories.id
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.id
     *
     * @param id the value for root_directories.id
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.directoriey_name
     *
     * @return the value of root_directories.directoriey_name
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public String getDirectorieyName() {
        return directorieyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.directoriey_name
     *
     * @param directorieyName the value for root_directories.directoriey_name
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setDirectorieyName(String directorieyName) {
        this.directorieyName = directorieyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.isUsed
     *
     * @return the value of root_directories.isUsed
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public String getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.isUsed
     *
     * @param isused the value for root_directories.isUsed
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setIsused(String isused) {
        this.isused = isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.create_date
     *
     * @return the value of root_directories.create_date
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.create_date
     *
     * @param createDate the value for root_directories.create_date
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.create_persion
     *
     * @return the value of root_directories.create_persion
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public String getCreatePersion() {
        return createPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.create_persion
     *
     * @param createPersion the value for root_directories.create_persion
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setCreatePersion(String createPersion) {
        this.createPersion = createPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.update_date
     *
     * @return the value of root_directories.update_date
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.update_date
     *
     * @param updateDate the value for root_directories.update_date
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.update_persion
     *
     * @return the value of root_directories.update_persion
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public String getUpdatePersion() {
        return updatePersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.update_persion
     *
     * @param updatePersion the value for root_directories.update_persion
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setUpdatePersion(String updatePersion) {
        this.updatePersion = updatePersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_directories.sys_id
     *
     * @return the value of root_directories.sys_id
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_directories.sys_id
     *
     * @param sysId the value for root_directories.sys_id
     *
     * @mbggenerated Sun Jul 10 22:01:42 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }
}