package com.may.mybatis.dao;

import com.may.mybatis.model.KeyVallueConfig;
import com.may.mybatis.model.KeyVallueConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeyVallueConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int countByExample(KeyVallueConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int deleteByExample(KeyVallueConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int insert(KeyVallueConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int insertSelective(KeyVallueConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    List<KeyVallueConfig> selectByExample(KeyVallueConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") KeyVallueConfig record, @Param("example") KeyVallueConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_Vallue_config
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExample(@Param("record") KeyVallueConfig record, @Param("example") KeyVallueConfigExample example);
}