package com.may.mybatis.dao;

import com.may.mybatis.model.ReleaseList;
import com.may.mybatis.model.ReleaseListExample;
import com.may.mybatis.model.ReleaseListWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int countByExample(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int deleteByExample(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int insert(ReleaseListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int insertSelective(ReleaseListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    List<ReleaseListWithBLOBs> selectByExampleWithBLOBs(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    List<ReleaseList> selectByExample(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReleaseListWithBLOBs record, @Param("example") ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ReleaseListWithBLOBs record, @Param("example") ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 06 11:08:22 CST 2016
     */
    int updateByExample(@Param("record") ReleaseList record, @Param("example") ReleaseListExample example);
}