package com.may.mybatis.dao;

import com.may.mybatis.model.ReleaseSystem;
import com.may.mybatis.model.ReleaseSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    int countByExample(ReleaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    int deleteByExample(ReleaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    int insert(ReleaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    int insertSelective(ReleaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    List<ReleaseSystem> selectByExample(ReleaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReleaseSystem record, @Param("example") ReleaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem
     *
     * @mbggenerated Wed Jul 13 20:29:42 CST 2016
     */
    int updateByExample(@Param("record") ReleaseSystem record, @Param("example") ReleaseSystemExample example);
}