package com.may.mybatis.dao;

import com.may.mybatis.model.ReleasePerson;
import com.may.mybatis.model.ReleasePersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleasePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int countByExample(ReleasePersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int deleteByExample(ReleasePersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int insert(ReleasePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int insertSelective(ReleasePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    List<ReleasePerson> selectByExampleWithBLOBs(ReleasePersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    List<ReleasePerson> selectByExample(ReleasePersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReleasePerson record, @Param("example") ReleasePersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ReleasePerson record, @Param("example") ReleasePersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasePerson
     *
     * @mbggenerated Wed Jul 13 11:08:10 CST 2016
     */
    int updateByExample(@Param("record") ReleasePerson record, @Param("example") ReleasePersonExample example);
}