package com.may.mybatis.dao;

import com.may.mybatis.model.ReleaseSystemPerson;
import com.may.mybatis.model.ReleaseSystemPersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseSystemPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int countByExample(ReleaseSystemPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int deleteByExample(ReleaseSystemPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int insert(ReleaseSystemPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int insertSelective(ReleaseSystemPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    List<ReleaseSystemPerson> selectByExample(ReleaseSystemPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReleaseSystemPerson record, @Param("example") ReleaseSystemPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releaseSystem_person
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExample(@Param("record") ReleaseSystemPerson record, @Param("example") ReleaseSystemPersonExample example);
}