package com.may.mybatis.dao;

import com.may.mybatis.model.ReleaseList;
import com.may.mybatis.model.ReleaseListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int countByExample(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int deleteByExample(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int insert(ReleaseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int insertSelective(ReleaseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    List<ReleaseList> selectByExampleWithBLOBs(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    List<ReleaseList> selectByExample(ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReleaseList record, @Param("example") ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ReleaseList record, @Param("example") ReleaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Release_list
     *
     * @mbggenerated Wed Jul 13 16:27:12 CST 2016
     */
    int updateByExample(@Param("record") ReleaseList record, @Param("example") ReleaseListExample example);
}